name: "aiforscience"

services:
  db:
    image: pgvector/pgvector:pg17
    container_name: db
    restart: no
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/db:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: s3
    restart: no
    environment:
      MINIO_ROOT_USER: ROOT_USER
      MINIO_ROOT_PASSWORD: TOOR_PASSWORD
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./volumes/minio/data:/data
    command: server /data --console-address ":9001"